### ISSUE TITLE
Why is there the same code with the same log message twice? "Found a table with the following pruefis"

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/kohlrahbi#150]
https://github.com/Hochfrequenz/kohlrahbi/blob/ab7b6712081a36cbfba0e2b18783736692fedb05/src/kohlrahbi/read_functions.py#L107

and 14 lines later:

https://github.com/Hochfrequenz/kohlrahbi/blob/ab7b6712081a36cbfba0e2b18783736692fedb05/src/kohlrahbi/read_functions.py#L121

Is one of them redundant?

**Comment by hf-krechan** [comment]
As of now, these lines seem to be gone.
This line is only in the `collect_pruefis.py` file and there only once :)

So I think I can close this issue.
