### ISSUE TITLE
Das ist 1:1 der Code der auch in der export funcition beautify_bedingungen steht. Ich nehme an, du kannst ihn an einer Stelle rausnehmen oder die Funktion aufrufen.

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/kohlrahbi#22]
Das ist 1:1 der Code der auch in der export funcition beautify_bedingungen steht. Ich nehme an, du kannst ihn an einer Stelle rausnehmen oder die Funktion aufrufen.

_Originally posted by @hf-aschloegl in https://github.com/Hochfrequenz/AHBExtractor/pull/5#discussion_r657201994_

**Comment by hf-krechan** [comment]
Jop ist gelöst. Das Ticket kann zu
