### ISSUE TITLE
Remove `section_name` From Flatahb If `segment_code` Is Empty

### ISSUE THREAD

**Issue by hf-krechan** [Hochfrequenz/kohlrahbi#339]
Today I learned: The name in the AHB documents on the left side is not the name of the segment group, it is the name of the segment.

So it doesn't make sense if we add this segment name in the lines, where we only have the segment group.

So the output for example of the `55001` should be

```json
{
      "ahb_expression": "Kann",
      "data_element": null,
      "guid": "fba40a12-c494-4105-847a-46f7b5f01ef3",
      "index": 25,
      "name": "",
      "section_name": null,  <-- I changed this line
      "segment_code": null,  <-- because the segment_code is null
      "segment_group_key": "SG3",
      "value_pool_entry": null
    },
    {
      "ahb_expression": "Muss",
      "data_element": null,
      "guid": "cca45667-760e-4d1d-a123-a30c7acda5e7",
      "index": 26,
      "name": "",
      "section_name": "Ansprechpartner",
      "segment_code": "CTA",
      "segment_group_key": "SG3",
      "value_pool_entry": null
    }
```
You can find the current output here: https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher/blob/51c7d93e77fafea60c1acb3a9b2ca5fe26c51206/FV2310/UTILMD/flatahb/55001.json#L245-L266

**Comment by DeltaDaniel** [comment]
This is related to https://github.com/Hochfrequenz/kohlrahbi/issues/336, right? :-)

**Comment by hf-kklein** [comment]
just to note it somewhere: IIRC, the maus MIG/ahb mapping is based on lines with section name only:
https://github.com/Hochfrequenz/mig_ahb_utility_stack/blob/502b82bbe6062a5d59e56e3cb7a3ea74bb524f19/src/maus/mig_ahb_matching.py#L197
