### ISSUE TITLE
Use MAUS Data Model: `FlatAnwendungshandbuch`

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/kohlrahbi#34]
We'd save one intermediate step if the AHBExtractor already used the MAUS data model, namely a [`FlatAnwendungshandbuch`](https://mig-ahb-utility-stack.readthedocs.io/en/stable/api/maus.models.html#maus.models.anwendungshandbuch.FlatAnwendungshandbuch). THis would save us from writing and reading csv, also we could spot data errors on AhbExtractor side already (instead when importing CSV in maus)

**Comment by hf-krechan** [comment]
I close this ticket because we have now the option to export the AHB as flatahb-json, csv and excel file.
