### ISSUE TITLE
kohlrahbi v1.5.3 schreibt ahb lines mit nur section_name und segment_code

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/kohlrahbi#421]
regression:

> kohlrahbi v1.5.3 dumpt lines mit nur section_name und segment_code. das war vorher nicht.

_Originally posted by @hf-kklein in https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher/pull/246#discussion_r1741424040_

**Comment by DeltaDaniel** [comment]
Fixed by https://github.com/Hochfrequenz/kohlrahbi/pull/427
