### ISSUE TITLE
kohlrahbi 1.5.3 nimmt einen empty string als default für segment-id. sollte null sein.

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/kohlrahbi#422]
regression: 
> kohlrahbi 1.5.3 nimmt einen empty string als default für segment-id. sollte null sein.

_Originally posted by @hf-kklein in https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher/pull/246#discussion_r1741423144_

**Comment by hf-krechan** [comment]
fixed by #435
