### ISSUE TITLE
`"Nachrichtenbeschreibung"` is `"Nachrichtenbeschreibun g"` since kohlrahbi 1.11

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/kohlrahbi#476]
@DeltaDaniel da haben wir wieder ne regression ;)

_Originally posted by @hf-kklein in https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher/pull/295#discussion_r1784065610_
            

probably caused by #474 , because that's the only relevant functional change https://github.com/Hochfrequenz/kohlrahbi/compare/v1.10.0...v1.11.0

**Comment by DeltaDaniel** [comment]
https://github.com/Hochfrequenz/kohlrahbi/pull/455 fixes this

**Comment by DeltaDaniel** [comment]
Not closed yet.
