### ISSUE TITLE
IFTSTA 21047 missing segments

### ISSUE THREAD

**Issue by OLILHR** [Hochfrequenz/kohlrahbi#482]
only 8/24 STS segments are available in the converted AHB: https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher/blob/3c3f961e1b006951ae237c54e05a711399def6cd/FV2504/IFTSTA/flatahb/21047.json#L536

![image](https://github.com/user-attachments/assets/93dcc7b2-dadf-4a4d-9ad0-5240cd9a8bf1)

**Comment by DeltaDaniel** [comment]
At the moment there are two valid versions on edi energy (e.g. IFTSTA FV2504: ...2.0f and ....2.0g). Kohlr_AHB_i will select now only the latest version.

**Comment by DeltaDaniel** [comment]
cf. https://github.com/Hochfrequenz/migmose/issues/160

**Comment by DeltaDaniel** [comment]
https://github.com/Hochfrequenz/kohlrahbi/pull/488
