### ISSUE TITLE
Read Filename where to expect the Pruefi from Excel Overview

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/kohlrahbi#82]
Es wäre tatsächlich möglich, wenn du diese datei einliest:
https://github.com/Hochfrequenz/edi_energy_mirror/blob/master/edi_energy_de/current/Anwendungs%C3%BCbersichtderPr%C3%BCfidentifikatoren-informatorischeLesefassung2.0Au%C3%9FerordentlicheVer%C3%B6ffentlichung_20230331_20221201.xlsx

das hieße aber extra aufwand den ich in diesem pr nicht machen würde. performance ist ja nicht unsere hauptprio (und wird es auch nie werden an der stelle)

_Originally posted by @hf-kklein in https://github.com/Hochfrequenz/kohlrahbi/pull/53#discussion_r1108674607_

**Comment by hf-krechan** [comment]
This issue is related to #148 and it got fixed in PR #209.

IMHO our current approach is also more resilient than the excel approach.
We use our own code to read all AHB files once. So we are 100% sure that the prüfis we are looking for are in the files we used.

So I close this issue :)
